# Makefile.macOS - Copyright (C) 2019, Jeremy Dilatush.  All rights reserved.
# Build "sockptyr" code for macOS: make -f Makefile.macOS

DYL=.dylib
DYLFLAGS=-dynamiclib -flat_namespace
CFLAGS=-g -Wall
sockptyr$(DYL): sockptyr_core.o
	$(CC) $(DYLFLAGS) -o $@ $^ -lc -ltcl
sockptyr_core.o: sockptyr_core.c
